name: cmc_nsidc0447
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9*
  - numpy >=1.20.0,<2.0.0a
  - matplotlib >=3.3.0,<4.0.0a
  - rasterio >=1.2.1,<2.0.0a
  - gdal >=3.1.0,<4.0.0a
